language: java
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: "ehiPVp9gJDaJnhlwrCbPb4t4ftzjIM+mTgtGOKrjAae+LcLkDde+AnfuU4T5J/lD/UhtHyTnNfqdDWy42HVzMQlCTsgjsLl7FOsglcmv/IFmcB28pIlJpbGVuLYrrb6iZU2VN293m8MC5g+BMAnjsJbWL8L9CAVZDF4Nz6mO4zyrHlC2ZRc4jVZhmsQ1dyiBy5f3leMh0OBQkUKTbP2OyzOJVNvfOgKK9epBWsPmwf+LOTMsBzetyxpZQMbul4RVeyngs7oHDDGxFat7+/gIwhIVq6I/K9W/H/1ESJxAQj8lYt/lDGrkB0QQF7Sv4ld0fCIK1lmFzX5LK0Cl7BaqIxc1j6KYkBRraDXPYhyrS05lSFMkIG5+yoLIRr07MitkQM4Qj9iV+1qhPzkzezvMbstHTMr9sGox10bt/wAydVffcGrFdFDCvXzB/UXCMUbpANrFYV5shG44IPDMUed7AsPUJQ2KhDv5S4USyXPV5RsLn1DGNnpYjQJQDKPYrgv6u6bxKsTdAs3WADOp6D8zhmI6lAIL+l6Tfd8s4lZVi34XjiVYJ9oNkyVf7HldvKT2FTwD/CuMwlGz7C+sPpHvbO4fjslLk1DzyU+d3w5KJ49WQKKalWi5K3h0avRBiqaSHosoKncu5+UTYbOvaysEPpPxVmuTw+mRRV+ltKg3lOo="
  app: kata-java-spring-xp
  on:
    repo: manikandanmuthuvs/kata-java-spring-xp
