language: java
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: Z4j9A1klYOVcDGZIS8f3TsqYCt0OlftnucOfoPYrAFjufrUBImzfXIPWJZ8icodGAlLr1I07BnMghy3v8C/yr7PWDf58a4Wjq9nAZomPupi4vnJd4Hb6VxR+lNoiUc812nsfimJssMov3XKK2M43RXHJys05Y/54YOVvJCoUqGLJ23oTS6RXOKH+vL7ud6smOsPJIZI1H9wg8J54chtoMZv9Xd0yyIvQwHlV94hCQsVvnnifsupbL5ySIKZDgv254qlx93iVWWdRPMvxeNNRA/wFTCE3inAffj7+knYQRvqgVBGk/R85GhqGwNGVACPrUkKqxfbUhyCGO/wlq3CpTNx7N9NZK68TMHTzytWaLnouuS5vAqFPuHHofeIE5BpcqjcJhMQAd4heWvbFWMAJZIi3Zh8hhypdFy4pMb7RgtPUluybFrDTPxqww3mjDAIlXqW9MOgAvi1Im/3v+QDrv0dBwk8JWGn4tYK+/SCQDeE5DcH5PouVbAvxs1ku2L5JppAnIaaE/3qohn86aZEchf7vGkJbnW/P2t5b0kCy/K913ircnQCaTvE38xNGjNld0G893ffCwELFX6l8Xr3JV9pOfXOLtVBJJ1ILqHRiLeKchAciwCKkUzYUcZpSvHvHx1kZlP4CIPIu7HAmJTpiVarvwptgt7fmLfzW7TFHj8c=
  app: kata-java-spring-xp
  on:
    repo: manikandanmuthuvs/kata-java-spring-xp
