language: java
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: 6b259f37-0c5d-4630-9da4-e257c586d0eb
  app: kata-java-spring-xp
  on:
    repo: manikandanmuthuvs/kata-java-spring-xp
